### PR TITLE
Allows adding a `frequency` (in minutes) to the options for each category

### PR DESCRIPTION
**Pull request by nhoizey**
For example, if you wanted to run audits for your `netlify` category every 10 minutes, you can add this:

```json
module.exports = {
  netlify: {
    description: "Netlify web sites",
    options: {
      freshChrome: "site",
      frequency: 10,
    },
    urls: [
      "https://www.netlify.com/",
      "https://www.netlify.com/donation-matching/",
      "https://www.netlify.com/products/build/plugins/",
      "https://www.netlify.com/with/sitecore/",
      "https://www.netlify.com/with/drupal/",
      "https://www.netlify.com/with/wordpress/",
      "https://www.netlify.com/webinar/a-drupal-journey-to-the-jamstack/",
      "https://jamstackconf.com/",
      "https://jamstackconf.com/virtual/",
    ],
  },
}
```

Runs timestamps are save in the same file.

There is a 60 minutes default.

### CODE REVIEW

**Comment by zachleat** [comment]
I like it—I think there are a lot of whitespace commits in there though?

**Comment by nhoizey** [comment]
Oooh sorry, you're right, my Prettier configuration is bad… 🤦‍♂️

I'll fix that.

**Comment by nhoizey** [comment]
@zachleat looks like it's fine now.

**Comment by zachleat** [comment]
Beautiful, thank you!

**Comment by nhoizey** [comment]
You're welcome!

**Pull request merged**
